# Generated by Django 4.1.3 on 2022-12-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiapps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
